Add Fm index
krzysztof-turowski/string-algorithms pull request #57
Opened 2024-03-15 20:21 UTC by prolik123

Added FM Index and unit tests

2024-03-15 20:22 UTC, prolik123 commented
Draft! 

Make refactor + write unit tests

2024-03-16 10:55 UTC, prolik123 commented on string_indexing/__pycache__/suffix_array.cpython-310.pyc
do usuniecia

2024-03-16 10:55 UTC, prolik123 commented on string_indexing/__pycache__/suffix_array.cpython-311.pyc
do usuniecia

2024-03-20 08:17 UTC, krzysztof-turowski requested changes
Thank you, please introduce appropriate changes and let me know if everything is clear.

FYI: `make check` provides you a linter check for all py files, it might be useful to you. In general the convention is as following: `function_name`, `_private_function_name` (i.e. helper, not used outside the package), `variable_name` + `ClassName` (but try to eliminate methods, use it only as C-like structs data holders)

2024-03-25 14:20 UTC, krzysztof-turowski commented on string_indexing/fm_index.py
> +    self.sample_size = 8 # const for sampling
Please make it a class-level constant:
```
class FMIndex:
  SAMPLE_SIZE = 8
```

2024-07-08 10:41 UTC, krzysztof-turowski approved these changes
Thank you very much for your contribution - well done!

2024-07-08 10:43 UTC, merged